apiVersion: batch/v1
kind: Job
metadata:
  name: train-iris
  namespace: mlops
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 180
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: train
        image: mlops-platform:dev
        imagePullPolicy: IfNotPresent
        command:
        - python
        - -m
        - mlops_platform.train
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow:5000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 768Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
