apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: predictor
        image: mlops-platform:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 768Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        command:
        - uvicorn
        args:
        - mlops_platform.api:app
        - --host
        - 0.0.0.0
        - --port
        - '8000'
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow:5000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        startupProbe:
          httpGet:
            path: /readyz
            port: 8000
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 60
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: predictor
spec:
  selector:
    app: predictor
  ports:
  - name: http
    port: 8000
    targetPort: 8000
